### ISSUE TITLE
Simple Data-fetching exercise not being rendered.

### ISSUE THREAD

**Issue by jorgeruvalcaba** [epicweb-dev/react-suspense#86]
The final example is not rendered and no error is displayed on the console.

![image](https://github.com/kentcdodds/react-suspense/assets/7416811/31bca17f-efb1-4a17-afc4-41626e62f811)

Seems that the server is not reachable:

![image](https://github.com/kentcdodds/react-suspense/assets/7416811/5f765bbd-3219-4109-8c02-ff9696fd46ed)

**Comment by kentcdodds** [comment]
Yes, that server is no longer supported, however, those requests should be handled by the service worker.

In any case, I've successfully reproduced the issue you're seeing here. What's really odd is I have no idea why it's happening. If you click "Open on isolated page" (which I recommend anyway), you should find that it should be working without issue there.

<img width="794" alt="image" src="https://github.com/kentcdodds/react-suspense/assets/1500684/73396708-8f76-4fca-9f69-b002ead8ff5e">

I'm pretty confused as to why the iframe isn't displaying because if you look at the dev tools all the DOM nodes are definitely there.

<img width="1360" alt="image" src="https://github.com/kentcdodds/react-suspense/assets/1500684/3072b6b6-fc92-49de-8c39-1863d38c284a">

Super weird.

**Comment by kentcdodds** [comment]
I'm revamping this completely and the issue will no longer exist when I'm finished.
